LANGUAGE_CHOICES = [
    ("en", "English"),
    ("fr", "French"),
    ("de", "German"),
    ("es", "Spanish"),
    ("it", "Italian"),
    ("pt", "Portuguese"),
    ("ru", "Russian"),
    ("zh", "Chinese"),
    ("ja", "Japanese"),
    ("ko", "Korean"),
    ("ar", "Arabic"),
    ("hi", "Hindi"),
    ("sw", "Swahili"),
    ("tr", "Turkish"),
    ("nl", "Dutch"),
    ("pl", "Polish"),
    ("sv", "Swedish"),
    ("no", "Norwegian"),
    ("fi", "Finnish"),
    ("el", "Greek"),
    ("he", "Hebrew"),
    ("th", "Thai"),
    ("vi", "Vietnamese"),
    ("id", "Indonesian"),
    ("fa", "Persian"),
    ("ur", "Urdu"),
    ("ot", "Other"),
]

GENRE_CHOICES = [
    ("ADVENTURE", "Adventure"),
    ("BIOGRAPHY", "Biography"),
    ("CHILDREN", "Children's"),
    ("CLASSIC", "Classic"),
    ("COMIC", "Comic / Graphic Novel"),
    ("CRIME", "Crime / Detective"),
    ("DRAMA", "Drama"),
    ("FANTASY", "Fantasy"),
    ("HISTORICAL", "Historical Fiction"),
    ("HORROR", "Horror"),
    ("LITERARY", "Literary Fiction"),
    ("MYSTERY", "Mystery"),
    ("NONFICTION", "Non-Fiction"),
    ("POETRY", "Poetry"),
    ("ROMANCE", "Romance"),
    ("SCIENCE", "Science"),
    ("SCIFI", "Science Fiction"),
    ("SELFHELP", "Self-Help"),
    ("SPIRITUALITY", "Spirituality / Religion"),
    ("THRILLER", "Thriller / Suspense"),
    ("TRAVEL", "Travel"),
    ("YOUNGADULT", "Young Adult"),
    ("PHILOSOPHY", "Philosophy"),
    ("TECHNOLOGY", "Technology"),
    ("COOKING", "Cooking"),
    ("ART", "Art / Photography"),
    ("HISTORY", "History"),
    ("EDUCATION", "Education"),
    ("BUSINESS", "Business / Economics"),
    ("HEALTH", "Health / Wellness"),
    ("POLITICS", "Politics / Current Affairs"),
]
