# Generated by Django 5.2.7 on 2025-12-13 19:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0008_alter_book_format"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checkout_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("due_date", models.DateTimeField(db_index=True)),
                ("returned_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ISSUED", "Issued"),
                            ("RETURN_REQUESTED", "Return Requested"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                ("is_ebook", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checkout_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="book_circul_user_id_704ec3_idx"
                    ),
                    models.Index(
                        fields=["book", "status"], name="book_circul_book_id_d00e20_idx"
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="book_circul_due_dat_357e33_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("returned_date__isnull", True),
                            ("status", "RETURNED"),
                            _negated=True,
                        ),
                        name="returned_status_requires_date",
                    )
                ],
            },
        ),
    ]
