# Generated by Django 5.2.7 on 2025-12-12 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_circulation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="due_date_after_checkout",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="checkout_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
