# Generated by Django 5.2.7 on 2025-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "book_circulation",
            "0002_remove_transaction_due_date_after_checkout_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ISSUED", "Issued"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURNED", "Returned"),
                ],
                db_index=True,
                default="ISSUED",
                max_length=20,
            ),
        ),
    ]
