# Generated by Django 5.2.7 on 2025-11-03 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ADVENTURE", "Adventure"),
                            ("BIOGRAPHY", "Biography"),
                            ("CHILDREN", "Children's"),
                            ("CLASSIC", "Classic"),
                            ("COMIC", "Comic / Graphic Novel"),
                            ("CRIME", "Crime / Detective"),
                            ("DRAMA", "Drama"),
                            ("FANTASY", "Fantasy"),
                            ("HISTORICAL", "Historical Fiction"),
                            ("HORROR", "Horror"),
                            ("LITERARY", "Literary Fiction"),
                            ("MYSTERY", "Mystery"),
                            ("NONFICTION", "Non-Fiction"),
                            ("POETRY", "Poetry"),
                            ("ROMANCE", "Romance"),
                            ("SCIENCE", "Science"),
                            ("SCIFI", "Science Fiction"),
                            ("SELFHELP", "Self-Help"),
                            ("SPIRITUALITY", "Spirituality / Religion"),
                            ("THRILLER", "Thriller / Suspense"),
                            ("TRAVEL", "Travel"),
                            ("YOUNGADULT", "Young Adult"),
                            ("PHILOSOPHY", "Philosophy"),
                            ("TECHNOLOGY", "Technology"),
                            ("COOKING", "Cooking"),
                            ("ART", "Art / Photography"),
                            ("HISTORY", "History"),
                            ("EDUCATION", "Education"),
                            ("BUSINESS", "Business / Economics"),
                            ("HEALTH", "Health / Wellness"),
                            ("POLITICS", "Politics / Current Affairs"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("author", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                ("edition", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("it", "Italian"),
                            ("pt", "Portuguese"),
                            ("ru", "Russian"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ko", "Korean"),
                            ("ar", "Arabic"),
                            ("hi", "Hindi"),
                            ("sw", "Swahili"),
                            ("tr", "Turkish"),
                            ("nl", "Dutch"),
                            ("pl", "Polish"),
                            ("sv", "Swedish"),
                            ("no", "Norwegian"),
                            ("fi", "Finnish"),
                            ("el", "Greek"),
                            ("he", "Hebrew"),
                            ("th", "Thai"),
                            ("vi", "Vietnamese"),
                            ("id", "Indonesian"),
                            ("fa", "Persian"),
                            ("ur", "Urdu"),
                            ("ot", "Other"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("total_copies", models.PositiveSmallIntegerField(default=1)),
                ("copies_available", models.PositiveSmallIntegerField(default=1)),
                (
                    "cover_image",
                    models.ImageField(
                        default="books/default_book.png", upload_to="books/"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="books.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
    ]
