# Generated by Django 5.2.7 on 2025-11-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="dewey_decimal",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="dimensions",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
