# Generated by Django 5.2.7 on 2025-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_dewey_decimal_book_dimensions_book_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="dewey_decimal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="dimensions",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
