# Generated by Django 5.2.7 on 2025-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(related_name="books", to="books.genre"),
        ),
    ]
