# Generated by Django 5.2.7 on 2025-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
