# Generated by Django 5.2.7 on 2025-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
