# Generated by Django 5.2.7 on 2025-12-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_book_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EBOOK", "E-Book"),
                    ("AUDIOBOOK", "Audio Book"),
                    ("HARDCOPY", "Hard copy"),
                ],
                default="HARDCOPY",
                max_length=50,
            ),
        ),
    ]
