# Generated by Django 5.2.7 on 2026-01-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_book_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
