# Generated by Django 5.2.7 on 2026-05-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                default="books/default_book.png", max_length=500, upload_to="books/"
            ),
        ),
    ]
