# Generated by Django 5.2.7 on 2025-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryuser",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/neutral.png", upload_to="profile_images/"
            ),
        ),
    ]
