# Generated by Django 5.2.7 on 2025-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_libraryuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
