# Generated by Django 5.2.7 on 2025-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_libraryuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="libraryuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="libraryuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
