# Generated by Django 5.2.7 on 2026-05-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_libraryuser_managers_alter_libraryuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openness",
                    models.FloatField(
                        default=0.5,
                        help_text="Openness to Experience (0=closed, 1=very open)",
                    ),
                ),
                (
                    "conscientiousness",
                    models.FloatField(
                        default=0.5,
                        help_text="Conscientiousness (0=disorganised, 1=very organised)",
                    ),
                ),
                (
                    "extraversion",
                    models.FloatField(
                        default=0.5,
                        help_text="Extraversion (0=introverted, 1=extraverted)",
                    ),
                ),
                (
                    "agreeableness",
                    models.FloatField(
                        default=0.5,
                        help_text="Agreeableness (0=competitive, 1=very cooperative)",
                    ),
                ),
                (
                    "neuroticism",
                    models.FloatField(
                        default=0.5,
                        help_text="Neuroticism (0=emotionally stable, 1=highly neurotic)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("assessment", "Psychometric Assessment"),
                            ("seeded", "System Seeded (Synthetic)"),
                            ("imported", "Imported"),
                        ],
                        default="assessment",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personality_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Personality Profile",
                "verbose_name_plural": "Personality Profiles",
            },
        ),
    ]
